theme: jekyll-theme-minimal
title: Teaching DSLC 
description: Fall 2022, teaching materials
logo: assets/img/yingli.png
show_downloads: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# Permalinks
permalink:        pretty

