## Setting up

### Import pandas and read in the csv file and set it to a dataframe called baskets

In [1]:
import pandas as pd
import numpy as np

In [2]:
baskets = pd.read_csv('baskets_sample_random_10.csv')

## Conduct basic data inspection

 - take a look at the first three rows, and last few rows

In [3]:
baskets.head(3)

id  order_id                placed_at               supplier_id  \
0  126        23  2021-05-05 11:04:46.579  5def2723b9a6b475bf66aac2   
1  166        41  2021-05-06 10:45:02.448  5def2723b9a6b475bf66aac2   
2  167        42  2021-05-06 10:45:04.850  5def2723b9a6b475bf66aac2   

   merchant_id  sku_id  top_cat_id  sub_cat_id  qty  price  
0           10     341         3.0        47.0  100    0.0  
1          196     341         3.0        47.0    2    0.0  
2          196     341         3.0        47.0    2    0.0

In [4]:
baskets.tail()

id  order_id                placed_at               supplier_id  \
29300  338870     61206  2022-07-31 16:52:33.731  5def2723b9a6b475bf66aac2   
29301  338871     61206  2022-07-31 16:52:33.731  5def2723b9a6b475bf66aac2   
29302  338872     61206  2022-07-31 16:52:33.731  5def2723b9a6b475bf66aac2   
29303  338873     61206  2022-07-31 16:52:33.731  5def2723b9a6b475bf66aac2   
29304  338874     61206  2022-07-31 16:52:33.731  5def2723b9a6b475bf66aac2   

       merchant_id  sku_id  top_cat_id  sub_cat_id  qty     price  
29300          428    1896         4.0        57.0   80   12350.0  
29301          428     747        12.0        36.0    1   86000.0  
29302          428     850         9.0        48.0    1  101500.0  
29303          428     853         9.0        48.0    1   68500.0  
29304          428     852         9.0        48.0    1   68500.0

### dataframe dimensions, column names, column data types, ranges of column values

In [5]:
baskets.shape

(29305, 10)

In [6]:
baskets.columns

Index(['id', 'order_id', 'placed_at', 'supplier_id', 'merchant_id', 'sku_id',
       'top_cat_id', 'sub_cat_id', 'qty', 'price'],
      dtype='object')

In [7]:
baskets.dtypes

id               int64
order_id         int64
placed_at       object
supplier_id     object
merchant_id      int64
sku_id           int64
top_cat_id     float64
sub_cat_id     float64
qty              int64
price          float64
dtype: object

 - noticed columns "placed_at" and "supplier_id" are not numeric and the rest are numerical columns

In [8]:
baskets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29305 entries, 0 to 29304
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           29305 non-null  int64  
 1   order_id     29305 non-null  int64  
 2   placed_at    29305 non-null  object 
 3   supplier_id  29305 non-null  object 
 4   merchant_id  29305 non-null  int64  
 5   sku_id       29305 non-null  int64  
 6   top_cat_id   29298 non-null  float64
 7   sub_cat_id   29298 non-null  float64
 8   qty          29305 non-null  int64  
 9   price        29305 non-null  float64
dtypes: float64(3), int64(5), object(2)
memory usage: 2.2+ MB


 - question: what can you observe from the above result?

 - why are the count on top_cat_id and sub_cat_id different from others? 

In [9]:
baskets.describe()

id      order_id   merchant_id        sku_id    top_cat_id  \
count   29305.000000  29305.000000  29305.000000  29305.000000  29298.000000   
mean   162948.006825  27337.267838   1061.053574    977.588671     10.860946   
std     95745.525000  18450.495064    761.056051    348.157681      8.353926   
min       126.000000     23.000000     10.000000      5.000000      1.000000   
25%     80106.000000  10296.000000    352.000000    755.000000      4.000000   
50%    158748.000000  25824.000000    934.000000    875.000000      9.000000   
75%    242651.000000  43776.000000   1717.000000   1055.000000     15.000000   
max    338874.000000  61439.000000   3160.000000   2383.000000     35.000000   

         sub_cat_id           qty         price  
count  29298.000000  2.930500e+04  2.930500e+04  
mean      50.808485  6.921692e+03  1.379133e+05  
std       31.280838  1.168396e+06  1.355361e+05  
min        1.000000  1.000000e+00  0.000000e+00  
25%       30.000000  1.000000e+00  4.550000e+04  
50%       48.000000  2.000000e+00  1.070000e+05  
75%       79.000000  5.000000e+00  1.845000e+05  
max      108.000000  2.000000e+08  2.175000e+06

 - noticed that the "placed_at" column was not shown in the above result, maybe due to its type?  
 - wondering that ID columns' statistics may not make sense other than count, min, max, since they are supposed to be identifiers

## Conduct some more data inspection

 - take a look at 3 random rows

In [10]:
# set seed for random function so that we get same rows when re-run the cell
np.random.seed(17)
baskets.iloc[np.random.randint(0, baskets.shape[0],3)]

id  order_id                placed_at               supplier_id  \
10863  121089     18116  2021-11-29 13:41:14.231  5def2723b9a6b475bf66aac2   
2191    24793      1959  2021-09-10 19:48:46.384  5def2723b9a6b475bf66aac2   
13702  150296     24073  2021-12-21 14:06:17.136  5def2723b9a6b475bf66aac2   

       merchant_id  sku_id  top_cat_id  sub_cat_id  qty    price  
10863         1304     768        14.0        37.0    3  85000.0  
2191           349     771        15.0        37.0    5  19200.0  
13702         1004     809         9.0        48.0  100  12000.0

 - take a look at transactions for a specific merchant_id

In [11]:
# set seed for random function so that we get same rows when re-run the cell
np.random.seed(17)
baskets[baskets['merchant_id'] == 1004]


id  order_id                placed_at               supplier_id  \
3063    33551      3158  2021-09-27 16:39:56.665  5def2723b9a6b475bf66aac2   
3064    33552      3158  2021-09-27 16:39:56.665  5def2723b9a6b475bf66aac2   
3065    33553      3158  2021-09-27 16:39:56.665  5def2723b9a6b475bf66aac2   
3066    33554      3158  2021-09-27 16:39:56.665  5def2723b9a6b475bf66aac2   
3067    33555      3158  2021-09-27 16:39:56.665  5def2723b9a6b475bf66aac2   
...       ...       ...                      ...                       ...   
20053  220679     39142  2022-02-15 17:03:14.776  5def2723b9a6b475bf66aac2   
20978  233205     42032  2022-02-24 09:31:28.591  5def2723b9a6b475bf66aac2   
20979  233206     42032  2022-02-24 09:31:28.591  5def2723b9a6b475bf66aac2   
20980  233207     42032  2022-02-24 09:31:28.591  5def2723b9a6b475bf66aac2   
20981  233208     42032  2022-02-24 09:31:28.591  5def2723b9a6b475bf66aac2   

       merchant_id  sku_id  top_cat_id  sub_cat_id  qty     price  
3063          1004    1289         4.0        31.0    1  292000.0  
3064          1004     875         3.0        80.0   10  168000.0  
3065          1004     778        15.0        53.0    5  137000.0  
3066          1004     889        35.0        98.0    5  224000.0  
3067          1004     724        12.0        30.0   75   16000.0  
...            ...     ...         ...         ...  ...       ...  
20053         1004    1758        12.0        12.0  210   24000.0  
20978         1004    1839        27.0        57.0    5  124000.0  
20979         1004    1838        15.0        57.0    5  125000.0  
20980         1004    1820         4.0        31.0    1   53000.0  
20981         1004    1821         5.0         9.0    1   59000.0  

[167 rows x 10 columns]

 - how much did it cost in total for merchant 1004?

In [12]:
baskets[baskets['merchant_id'] == 1004].price.sum()

24238650.0

 - what is the average price for order 3158?

In [13]:
baskets[baskets['order_id'] == 3158].price.mean()

145583.33333333334

 - what are the average price, min and max prices for all rows in this dataset?

In [14]:
baskets['price'].mean(), baskets['price'].min(), baskets['price'].max(), 

(137913.33466782197, 0.0, 2175000.0)

 - how many rows have price of 0
 - question: Why would some items have price of 0? 

*** TODO: find out why would some items have price of 0?
  

In [15]:
baskets[baskets['price']==0].count()

id             520
order_id       520
placed_at      520
supplier_id    520
merchant_id    520
sku_id         520
top_cat_id     519
sub_cat_id     519
qty            520
price          520
dtype: int64

 - check columns' number of unique values

In [16]:
baskets.nunique()

id             29303
order_id        5542
placed_at       5541
supplier_id        1
merchant_id      317
sku_id          1353
top_cat_id        32
sub_cat_id        90
qty              174
price           1114
dtype: int64

- question: what can you observe from the above result? what might seem to be peculiar? 

 - notice unique placed_at is one greater than unique order_id
 - question: is it possible that two orders are made on exactly the same milisecond? In theory it is possible, but might there be potential fraud?

  *** TODO: how can we find out which two orders happened on the exact same millisecond? 


 - can we check the min and max of "date" column?

In [17]:
baskets['placed_at'].min(), baskets['placed_at'].max()

('2021-05-05 11:04:46.579', '2022-07-31 16:52:33.731')

 - how many merchant transacted on a particular day, say December 31, 2021?
 - what is the type "object" anyways?

In [18]:
baskets['placed_at'][1], type(baskets['placed_at'][1])

('2021-05-06 10:45:02.448', str)

 - how do we work with a string object and get the date, hour, min, second, millisecond?

### gather all observations, questions, and TODOs

 - columns "placed_at" and "supplier_id" are not numeric and the rest are numerical columns
 - why are the count on top_cat_id and sub_cat_id different from others? 
 - ID columns' statistics make sense other than count, min, max, since they are supposed to be identifiers, should we treat them as categorical?
 - why would some items have price of 0?
 - unique placed_at is one greater than unique order_id
 - is it possible that two orders are made on exactly the same milisecond? In theory it is possible, but might there be potential fraud?
 - how can we find out which two orders happened on the exact same millisecond? 
 - how many merchant transacted on a particular day, say December 31, 2021?
 - how do we work with a string object and get the date, hour, min, second, millisecond? 